package exception;

public class ExceptionExam01 {


	public static void main(String[] args) {
//		int a = 5;
//		int b = 0;
//		int[] arr = {10,20};
//		int[] test;
//		String arrTest = null; //아직 참조하는 객체가 없다.
		
//		for(int i = 0; i < arr.length; i++) {
//			System.out.println(arr[i]);
//			arr[i+1] =  i + 30; //java.lang.ArrayIndexOutOfBoundsException
//		}
		
//		for(int i = 0; i < test.length; i++) { //일반예외 - 컴파일 전 예외 확인 가능
//			test[i] = i+20;
//			System.out.println(test[i]);
//		}
		
//		System.out.println(a/b); //java.lang.ArithmeticException
		
//		System.out.println(arrTest.toString()); //java.lang.NullPointerException
		
	}

}
